                                             Modules                                                                         

In Python (and many programming languages), **packages** and **modules** help organize code. Here's the difference between **internal** and **external packages/modules**:

---

### 🔸 Internal Packages and Modules (Built-in or Standard Library)

* **Definition**: These are **pre-installed** with Python. You don't need to install them separately.
* **Examples**:

  * `math` – for mathematical functions
  * `os` – for interacting with the operating system
  * `datetime` – for date and time manipulation
* **Usage**:

  ```python
  import math
  print(math.sqrt(25))  # Output: 5.0
  ```

---

### 🔸 External Packages and Modules (Third-party)

* **Definition**: These are **not included** with Python. You need to install them using tools like `pip`.
* **Examples**:

  * `numpy` – for numerical computations
  * `pandas` – for data analysis
  * `requests` – for HTTP requests
* **Installation**:

  ```
  pip install numpy
  ```
* **Usage**:

  ```python
  import numpy as np
  print(np.array([1, 2, 3]))
  ```

---

### Summary Table

| Feature       | Internal (Standard)     | External (Third-party)      |
| ------------- | ----------------------- | --------------------------- |
| Pre-installed | Yes                     | No                          |
| Installation  | Not required            | Required via `pip`          |
| Examples      | `os`, `sys`, `math`     | `numpy`, `flask`, `pandas`  |
| Source        | Python Standard Library | PyPI (Python Package Index) |




                                                    NumPy                                                                                           

### What is NumPy?

**NumPy** (Numerical Python) is an open-source Python library used for working with **numerical data**, especially large, multi-dimensional arrays and matrices. It also provides a large collection of **mathematical functions** to operate on these arrays.

---

### Key Features of NumPy:

| Feature                            | Description                                                      |
| ---------------------------------- | ---------------------------------------------------------------- |
| **n-dimensional arrays (ndarray)** | Core data structure for fast, flexible container of large data.  |
| **Broadcasting**                   | Perform arithmetic on arrays of different shapes.                |
| **Vectorized operations**          | Faster operations without using Python loops.                    |
| **Mathematical functions**         | Functions like `mean()`, `std()`, `sum()`, `exp()`, etc.         |
| **Linear Algebra**                 | Supports operations like dot product, inverse, eigenvalues, etc. |
| **Random Module**                  | Generate random numbers, sampling, distributions, etc.           |
| **Integration with C/C++**         | Can be extended with C/C++ for performance.                      |
| **Memory Efficient**               | Stores data more compactly than built-in Python lists.           |

---

### Why Use NumPy?

* Much **faster** than standard Python lists for numeric computations.
* Backbone for **data science** libraries like Pandas, SciPy, Scikit-Learn, TensorFlow, etc.
* Reduces the need for **explicit loops** with vectorized operations.
* Essential for **scientific computing**, simulations, machine learning, image processing, etc.

---

### NumPy Array vs Python List

| Feature        | NumPy Array            | Python List           |
| -------------- | ---------------------- | --------------------- |
| Type           | Homogeneous            | Heterogeneous         |
| Speed          | Very fast              | Slower                |
| Memory usage   | Less                   | More                  |
| Operations     | Element-wise supported | Manual looping needed |
| Dimensionality | Multi-dimensional      | Mostly 1D or nested   |

---

### Example Code:

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# Basic math operation
print("Array squared:", arr ** 2)

# Create 2D array
matrix = np.array([[1, 2], [3, 4]])
print("2D Matrix:\n", matrix)

# Mean and standard deviation
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Generate random numbers
random_array = np.random.rand(3, 3)
print("Random 3x3 Matrix:\n", random_array)
```

---

### Real-World Applications:

* **Data Analysis** (with Pandas)
* **Image processing** (pixels as arrays)
* **Machine Learning** (features and weights as vectors/matrices)
* **Simulations** and numerical modeling
* **Engineering calculations** and **signal processing**



In [1]:
import numpy

In [2]:
import numpy as np

In [8]:
import numpy as numpy
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

# print("Squared Array ", arr**2)

# matrix=([1,2,3],[5,6,7])
# print("Matrix ", matrix)

[1 2 3 4]
<class 'numpy.ndarray'>


Create NumPy n-d array Objects
the array is called ndarray

Dimention in array , 0 Dimention,1D,2D

In [17]:
import numpy as np
import numpy as numpy
arr=np.array([1,2,3,4])
print("One D Array",arr)
# print("Squared Array ", arr**2)

matrix=([1,2,3],[5,6,7])
print("2D array ", matrix)

matrix=([1,2,3],[3,4,5],[5,6,7])
print("3d Array Is: ", matrix)

One D Array [1 2 3 4]
2D array  ([1, 2, 3], [5, 6, 7])
3d Array Is:  ([1, 2, 3], [3, 4, 5], [5, 6, 7])


In [21]:
import numpy as np
arr = np.array([[[1,2,3],[1,7,8]],[[5,9,8],[4,5,6]]])
print("3D Array Is: ", arr)

3D Array Is:  [[[1 2 3]
  [1 7 8]]

 [[5 9 8]
  [4 5 6]]]


Check Dimention in array

In [22]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[5,6,7]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimention array

In [27]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Number of Dimentions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimentions:  5


NUMPY Array Indexing

In [29]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[2]+arr[3])

[1 2 3 4]
1
7


Acces Element from 2D array

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd Elemnet of 1st Row: ",arr[0,1])
print("5nd Elemnet of 2st Row: ",arr[1,4])

2nd Elemnet of 1st Row:  2
5nd Elemnet of 2st Row:  10


Access From 3D

In [34]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [36]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5


SLICING

[start:end]
[start:end:step]

In [40]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:3])
print(arr[2:])
print(arr[:8])
print(arr)
print(arr[-2:-1])
print(arr[1:8:2])

[2 3]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[9]
[2 4 6 8]


Slicing 2D array

In [47]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0:1,0:1])
print(arr[0:1,1:3])
print(arr[0:3,1:2])
print(arr[0:4,1:1])
print(arr[0:5,1:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1]]
[[2 3]]
[[2]
 [7]]
[]
[[ 2  3  4  5]
 [ 7  8  9 10]]


ITERATion

In [49]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [50]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in arr:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
