                                             Modules                                                                         

In Python (and many programming languages), **packages** and **modules** help organize code. Here's the difference between **internal** and **external packages/modules**:

---

### 🔸 Internal Packages and Modules (Built-in or Standard Library)

* **Definition**: These are **pre-installed** with Python. You don't need to install them separately.
* **Examples**:

  * `math` – for mathematical functions
  * `os` – for interacting with the operating system
  * `datetime` – for date and time manipulation
* **Usage**:

  ```python
  import math
  print(math.sqrt(25))  # Output: 5.0
  ```

---

### 🔸 External Packages and Modules (Third-party)

* **Definition**: These are **not included** with Python. You need to install them using tools like `pip`.
* **Examples**:

  * `numpy` – for numerical computations
  * `pandas` – for data analysis
  * `requests` – for HTTP requests
* **Installation**:

  ```
  pip install numpy
  ```
* **Usage**:

  ```python
  import numpy as np
  print(np.array([1, 2, 3]))
  ```

---

### Summary Table

| Feature       | Internal (Standard)     | External (Third-party)      |
| ------------- | ----------------------- | --------------------------- |
| Pre-installed | Yes                     | No                          |
| Installation  | Not required            | Required via `pip`          |
| Examples      | `os`, `sys`, `math`     | `numpy`, `flask`, `pandas`  |
| Source        | Python Standard Library | PyPI (Python Package Index) |




                                                    NumPy                                                                                           

### What is NumPy?

**NumPy** (Numerical Python) is an open-source Python library used for working with **numerical data**, especially large, multi-dimensional arrays and matrices. It also provides a large collection of **mathematical functions** to operate on these arrays.

---

### Key Features of NumPy:

| Feature                            | Description                                                      |
| ---------------------------------- | ---------------------------------------------------------------- |
| **n-dimensional arrays (ndarray)** | Core data structure for fast, flexible container of large data.  |
| **Broadcasting**                   | Perform arithmetic on arrays of different shapes.                |
| **Vectorized operations**          | Faster operations without using Python loops.                    |
| **Mathematical functions**         | Functions like `mean()`, `std()`, `sum()`, `exp()`, etc.         |
| **Linear Algebra**                 | Supports operations like dot product, inverse, eigenvalues, etc. |
| **Random Module**                  | Generate random numbers, sampling, distributions, etc.           |
| **Integration with C/C++**         | Can be extended with C/C++ for performance.                      |
| **Memory Efficient**               | Stores data more compactly than built-in Python lists.           |

---

### Why Use NumPy?

* Much **faster** than standard Python lists for numeric computations.
* Backbone for **data science** libraries like Pandas, SciPy, Scikit-Learn, TensorFlow, etc.
* Reduces the need for **explicit loops** with vectorized operations.
* Essential for **scientific computing**, simulations, machine learning, image processing, etc.

---

### NumPy Array vs Python List

| Feature        | NumPy Array            | Python List           |
| -------------- | ---------------------- | --------------------- |
| Type           | Homogeneous            | Heterogeneous         |
| Speed          | Very fast              | Slower                |
| Memory usage   | Less                   | More                  |
| Operations     | Element-wise supported | Manual looping needed |
| Dimensionality | Multi-dimensional      | Mostly 1D or nested   |

---

### Example Code:

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# Basic math operation
print("Array squared:", arr ** 2)

# Create 2D array
matrix = np.array([[1, 2], [3, 4]])
print("2D Matrix:\n", matrix)

# Mean and standard deviation
print("Mean:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Generate random numbers
random_array = np.random.rand(3, 3)
print("Random 3x3 Matrix:\n", random_array)
```

---

### Real-World Applications:

* **Data Analysis** (with Pandas)
* **Image processing** (pixels as arrays)
* **Machine Learning** (features and weights as vectors/matrices)
* **Simulations** and numerical modeling
* **Engineering calculations** and **signal processing**



In [1]:
import numpy

In [2]:
import numpy as np

In [8]:
import numpy as numpy
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

# print("Squared Array ", arr**2)

# matrix=([1,2,3],[5,6,7])
# print("Matrix ", matrix)

[1 2 3 4]
<class 'numpy.ndarray'>


Create NumPy n-d array Objects
the array is called ndarray

Dimention in array , 0 Dimention,1D,2D

In [17]:
import numpy as np
import numpy as numpy
arr=np.array([1,2,3,4])
print("One D Array",arr)
# print("Squared Array ", arr**2)

matrix=([1,2,3],[5,6,7])
print("2D array ", matrix)

matrix=([1,2,3],[3,4,5],[5,6,7])
print("3d Array Is: ", matrix)

One D Array [1 2 3 4]
2D array  ([1, 2, 3], [5, 6, 7])
3d Array Is:  ([1, 2, 3], [3, 4, 5], [5, 6, 7])


In [21]:
import numpy as np
arr = np.array([[[1,2,3],[1,7,8]],[[5,9,8],[4,5,6]]])
print("3D Array Is: ", arr)

3D Array Is:  [[[1 2 3]
  [1 7 8]]

 [[5 9 8]
  [4 5 6]]]


Check Dimention in array

In [22]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5,6])
c=np.array([[1,2,3],[5,6,7]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimention array

In [27]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Number of Dimentions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimentions:  5


NUMPY Array Indexing

In [29]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)
print(arr[0])
print(arr[2]+arr[3])

[1 2 3 4]
1
7


Acces Element from 2D array

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd Elemnet of 1st Row: ",arr[0,1])
print("5nd Elemnet of 2st Row: ",arr[1,4])

2nd Elemnet of 1st Row:  2
5nd Elemnet of 2st Row:  10


Access From 3D

In [34]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [36]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5


SLICING

[start:end]
[start:end:step]

In [40]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[1:3])
print(arr[2:])
print(arr[:8])
print(arr)
print(arr[-2:-1])
print(arr[1:8:2])

[2 3]
[ 3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[9]
[2 4 6 8]


Slicing 2D array

In [47]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0:1,0:1])
print(arr[0:1,1:3])
print(arr[0:3,1:2])
print(arr[0:4,1:1])
print(arr[0:5,1:5])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1]]
[[2 3]]
[[2]
 [7]]
[]
[[ 2  3  4  5]
 [ 7  8  9 10]]


ITERATION

In [49]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [50]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in arr:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


Each Elements

In [1]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10


In [2]:
#in 3D Array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print("X represents the 2D array: ")
    print(x)

X represents the 2D array: 
[[1 2 3]
 [4 5 6]]
X represents the 2D array: 
[[ 7  8  9]
 [10 11 12]]


In [3]:
#iteration down to scaler
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


Iteration using nditer()


                                                            QUESTIONS:                                                                          

How do you create 1D array

In [6]:
import numpy as np
arr= np.array([1,2,3,4,5])
print("1D Array: ",arr)

1D Array:  [1 2 3 4 5]


how do you reshape 1D array to 9 elements into 3x3 2D array

In [7]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array: ", arr1)

2D Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


how do you find maximum elemts in an array

In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
m=len(arr)
print(m)

11


what is the diff between module and package give five points



| Feature                | Module                        | Package                                           |
| ---------------------- | ----------------------------- | ------------------------------------------------- |
| **Definition**         | A single Python file (`.py`)  | A directory/folder containing multiple modules    |
| **Structure**          | Flat (just one `.py` file)    | Hierarchical (folder with multiple `.py` files)   |
| **File Example**       | `math_utils.py`               | `mypackage/` with `__init__.py`, `utils.py`, etc. |
| **Contains**           | Functions, classes, variables | One or more modules and `__init__.py` file        |
| **Use Case**           | Code reuse within one file    | Organizing large codebase with related modules    |
| **Import Example**     | `import math_utils`           | `from mypackage import utils`                     |
| **Special File**       | No special file needed        | Must contain `__init__.py`                        |
| **Real-world Example** | `os.py`, `math.py`            | `numpy`, `pandas` packages                        |




create an array of 10 elements all equals to 5


In [11]:
import numpy as np
element=[]
for i in range(1,11):
    element.append(5)
print("Array: ", element)

Array:  [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


Datatype of array


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
m=type(arr)
print(m)

<class 'numpy.ndarray'>


Iteration in 3d Using nditer

In [13]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10


Iteration With Different datatype

op_dtypes()
iteration through array as a string

In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')


In [22]:
import numpy as np
arr=np.array([[11,12,13],[14,15,16]])

print("Array is of type: {}".format(type(arr)))
print("Number of dimentions: {}".format(arr.ndim))
print("Shape of array {}".format(arr.shape))
print("Size of array: {}".format(arr.size))
print("Data type of array:{} ".format(arr.dtype))

Array is of type: <class 'numpy.ndarray'>
Number of dimentions: 2
Shape of array (2, 3)
Size of array: 6
Data type of array:int64 


In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


REmove element from array

In [29]:
import numpy as np
arr=np.array([i for i in range(50)])
print("oRIGINAL Array: ", "\n",arr)
m=[i for i in range (50) if i%5==0]

res=np.delete(arr,m)
print("Array after deleting elements: ", "\n", res)


oRIGINAL Array:  
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Array after deleting elements:  
 [ 1  2  3  4  6  7  8  9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 28 29
 31 32 33 34 36 37 38 39 41 42 43 44 46 47 48 49]


use zeros()

In [32]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


the import creams excel point to remamber their ARTICLES

In [33]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.dtype


dtype('int64')

In [37]:
arr.shape

(3, 3)

In [38]:
arr.size

9

In [39]:
np.array({3,4,5})

array({3, 4, 5}, dtype=object)

In [41]:
zeros=np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
zeros.dtype

dtype('float64')

In [43]:
zeros.shape

(4, 5)

In [45]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
linspace=np.linspace(3,5,12)
linspace

array([3.        , 3.18181818, 3.36363636, 3.54545455, 3.72727273,
       3.90909091, 4.09090909, 4.27272727, 4.45454545, 4.63636364,
       4.81818182, 5.        ])

In [50]:
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.33772113e-307, 4.45050422e-308, 1.89146896e-307],
       [7.56571288e-307, 4.00544531e-307, 1.11261095e-306,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037317e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 9.34608432e-307, 1.11260144e-306,
        6.89812281e-307, 2.22522596e-306, 7.23188049e-308]])

In [51]:
id=np.identity(45)
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
id.shape

(45, 45)

In [55]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [58]:
arr.shape

(99,)

In [59]:
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
arr.sum(axis=0)

array([12, 15, 18])

In [61]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [62]:
arr.T # transpose the array(row convet in coloum and coloum convert into row)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [64]:
arr.flat #means iterator

In [65]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [66]:
arr.ndim

2

In [67]:
arr.size

9

In [68]:
arr.nbytes

72

In [71]:
one=np.array([1,2,3,445,6])
one.argmax()

np.int64(3)

In [72]:
one.argmin

<function ndarray.argmin>

In [73]:
one.argsort()

array([0, 1, 2, 4, 3])

In [74]:
import numpy as np

x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [76]:
import numpy as np

#Step 1 create a 3D numpy Arary with students
# 5 students , 4 subjects(Maths , science , English , History)

marks=np.array([
    [85,78,89,88],
    [85,78,89,88],
    [85,78,89,88],
    [85,78,89,88],
    [85,78,89,88]
])

students=['Rohit', 'Atul', 'Harsh', 'Muskan', 'Mridul']
subjects=['Math','Science','English','History']

#Step 2 print Max marks
print("\n Marks Matrix: \n")
print(marks)

#Step 3 calculate average marks of each student

avg_per_student=np.mean(marks,axis=1)
print("\n Aerage Marks Per Student: \n")
for i , avg in enumerate(avg_per_student):
    print(f"{students[i]}:{avg: .2f}")

#Step 4 clculate avg marks per students
avg_per_subject=np.mean(marks,axis=0)
print(" \nAverage Marks per students: \n")
for i , avg in enumerate(avg_per_subject):
    print(f"{subjects[i]}:{avg:.2f}")

#Step 5 find the top scorer
print("\n Top scorer in each subjects: \n")
for i in range(len(subjects)):
    top_student_index=np.argmax(marks[:,i])
    print(f"{subjects[i]}:{students[top_student_index]} ({marks[top_student_index,i]})")

#Step 6 find min and max per subj
print("\n Min and max marks per subjects: \n")
for i, subjects in enumerate(subjects):
    min_marks = np.min(marks[:,i])
    max_marks = np.max(marks[:,i])
    print(f"{subjects}: min={min_marks}, max={max_marks}")




 Marks Matrix: 

[[85 78 89 88]
 [85 78 89 88]
 [85 78 89 88]
 [85 78 89 88]
 [85 78 89 88]]

 Aerage Marks Per Student: 

Rohit: 85.00
Atul: 85.00
Harsh: 85.00
Muskan: 85.00
Mridul: 85.00
 
Average Marks per students: 

Math:85.00
Science:78.00
English:89.00
History:88.00

 Top scorer in each subjects: 

Math:Rohit (85)
Science:Rohit (78)
English:Rohit (89)
History:Rohit (88)

 Min and max marks per subjects: 

Math: min=85, max=85
Science: min=78, max=78
English: min=89, max=89
History: min=88, max=88
